#!/usr/bin/env python

import sys
import socket
import struct
import datetime
from influxdb import InfluxDBClient

#
# Constants
#
kPORT = 7820
kNCH = 48
kUNITSIZE = 4
kMESSLEN = 100*kUNITSIZE
kHVMON = 2

'''
kINFHOST = 
kINFPORT = 
kINFUSER = 
kINFPASS = 
kINFDBNAME = 
'''

current_time = datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')

connection = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
try:
    connection.connect(('localhost', kPORT))
except socket.error as e:
    sys.exit(1)


cmd = struct.pack('2i', kHVMON, 0)
connection.send(cmd)
buf = connection.recv(2*kNCH*kUNITSIZE)
values = struct.unpack('%df' % (2*kNCH), buf)

valdict = {}
for i in range(kNCH):
    id = i+1
    valdict['V_%d' % id] = values[i]
    valdict['I_%d' % id] = values[i+kNCH]

point = [
    {
        "measurement": "hvstat",
        "time": current_time,
        "fields": valdict
    }
]

'''
influx = InfluxDBClient(kINFHOST, kINFPORT, kINFUSER, kINFPASS, kINFDBNAME)
influx.write_points(point)
influx.close()
'''
